stages:
  - release

release_patch_and_push:
  stage: release
  image: node:22-alpine
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
      when: manual
    - when: never
  before_script:
    - apk add --no-cache git openssh-client
    - git config user.name "${GIT_USER_NAME:-bot}" && git config user.email "${GIT_USER_EMAIL:-ci-pip@limits.trade}"
    # Ensure we are on a branch rather than detached HEAD
    - |
      if [ -n "$CI_COMMIT_BRANCH" ]; then
        git checkout -B "$CI_COMMIT_BRANCH"
      fi
    # Ensure GitHub remote exists and uses token auth
    - |
      if ! git remote | grep -q "^github$"; then
        git remote add github "https://${GITHUB_USER:-git}:${GITHUB_TOKEN}@${GITHUB_HOST:-github.com}/${GITHUB_REPOSITORY}.git"
      else
        git remote set-url github "https://${GITHUB_USER:-git}:${GITHUB_TOKEN}@${GITHUB_HOST:-github.com}/${GITHUB_REPOSITORY}.git"
      fi
  script:
    - 'npm version patch -m "chore(release): %s [skip ci]"'
    - git push github "${CI_COMMIT_BRANCH}" --follow-tags
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
